version: '3.1'

services:

  # db:
  #   image: postgres:15
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - 5432:5432

  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "
      cron &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    # depends_on:
    #   - db
