# Generated by Django 5.0.5 on 2024-06-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlebot",
            name="image_template",
            field=models.CharField(
                default="",
                help_text="The template used when asking ai to generate image",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
