# Generated by Django 5.0.5 on 2024-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
