# Generated by Django 5.0.5 on 2024-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_price_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
